# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='宠物描述')),
                ('publish_time', models.DateField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('province', models.CharField(blank=True, max_length=10, null=True, verbose_name='省份')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='详细地址')),
                ('pet', models.ManyToManyField(related_name='Publishs', to='pet.Pet')),
            ],
            options={
                'verbose_name': '领养信息',
                'verbose_name_plural': '领养信息',
                'ordering': ('-publish_time',),
            },
        ),
    ]
