# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.DurationField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('cat', '猫'), ('dog', '狗')], max_length=3)),
                ('adopted', models.BooleanField(default=False)),
                ('size', models.CharField(choices=[('large', '大型'), ('medium', '中等体型'), ('small', '小型')], max_length=6)),
                ('add_time', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '宠物',
                'verbose_name_plural': '宠物',
                'ordering': ('-add_time',),
            },
        ),
    ]
